/** Export sample report artifacts from the browser state left by record_demo.mjs. */
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

const port = process.env.DEMO_CDP_PORT || '9229';
const targets = await fetch(`http://127.0.0.1:${port}/json/list`).then(response => response.json());
const target = targets.find(item => item.type === 'page' && item.webSocketDebuggerUrl);
if (!target) throw new Error('No Chrome debugging page found. Run record_demo.mjs first.');
const socket = new WebSocket(target.webSocketDebuggerUrl);
await new Promise((resolve, reject) => {
  socket.addEventListener('open', resolve, { once: true });
  socket.addEventListener('error', reject, { once: true });
});
let nextId = 1;
const pending = new Map();
socket.addEventListener('message', event => {
  const message = JSON.parse(event.data);
  const callback = pending.get(message.id);
  if (!callback) return;
  pending.delete(message.id);
  message.error ? callback.reject(new Error(message.error.message)) : callback.resolve(message.result);
});
const call = (method, params = {}) => new Promise((resolve, reject) => {
  const id = nextId++;
  pending.set(id, { resolve, reject });
  socket.send(JSON.stringify({ id, method, params }));
});
const evaluate = async expression => {
  const reply = await call('Runtime.evaluate', { expression, returnByValue: true });
  if (reply.exceptionDetails) throw new Error(reply.exceptionDetails.text);
  return reply.result.value;
};
const downloadDir = await fs.mkdtemp(path.join(os.tmpdir(), 'ipsec-report-export-'));
const outputDir = path.join(process.cwd(), 'demo');
const capture = path.join(process.cwd(), 'pcap_factory', 'captures', 'AES128_SHA256_DH14_NOPFS_ICMP_rep01.pcap');
const waitFor = async (expression, timeoutMs = 30000) => {
  const started = Date.now();
  while (Date.now() - started < timeoutMs) {
    if (await evaluate(expression)) return;
    await new Promise(resolve => setTimeout(resolve, 400));
  }
  throw new Error(`Timed out waiting for ${expression}`);
};
const waitForDownload = async (kind, extension) => {
  const started = Date.now();
  while (Date.now() - started < 15000) {
    const names = await fs.readdir(downloadDir);
    const match = names.find(name => name.endsWith(`_${kind}.${extension}`));
    if (match) return path.join(downloadDir, match);
    await new Promise(resolve => setTimeout(resolve, 250));
  }
  throw new Error(`Report ${kind}.${extension} did not download.`);
};

try {
  await call('Runtime.enable');
  await call('Page.enable');
  await call('DOM.enable');
  await call('Browser.setDownloadBehavior', { behavior: 'allow', downloadPath: downloadDir });
  if (!await evaluate("!!document.querySelector('#btn-report-tech')")) {
    await call('Page.navigate', { url: 'http://127.0.0.1:3000' });
    await waitFor("!!document.querySelector('#dropzone-file')");
    const input = await call('Runtime.evaluate', { expression: "document.querySelector('#dropzone-file')", returnByValue: false });
    await call('DOM.setFileInputFiles', { objectId: input.result.objectId, files: [capture] });
    await waitFor("!!document.querySelector('#btn-quick-report')");
    await evaluate("document.querySelector('#btn-quick-report').click()");
    await waitFor("!!document.querySelector('#btn-report-tech')");
    await waitFor("document.body.innerText.includes('Generated by GROQ_LLM') || document.body.innerText.includes('AI narrative unavailable')", 30000);
  }
  const exports = [];
  for (const [kind, selector] of [['executive', '#btn-report-exec'], ['technical', '#btn-report-tech']]) {
    await evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
    await evaluate("document.querySelector('#btn-download-pdf').click()");
    exports.push([await waitForDownload(kind, 'pdf'), path.join(outputDir, `sample-${kind}-report.pdf`)]);
    await evaluate("document.querySelector('#btn-download-report').click()");
    exports.push([await waitForDownload(kind, 'md'), path.join(outputDir, `sample-${kind}-report.md`)]);
  }
  for (const [source, destination] of exports) await fs.copyFile(source, destination);
  console.log('Exported sample executive and technical PDF and Markdown reports.');
} finally {
  socket.close();
}
