/** Record a short, silent walkthrough from the running local prototype.
 * Start Chrome with --headless=new --remote-debugging-port=9229 and open
 * http://127.0.0.1:3000 before running `node demo/record_demo.mjs`.
 * Uses only Node and Chrome; no screen recording dependency is required.
 */
import fs from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd();
const demoDir = path.join(root, 'demo');
const capture = path.join(root, 'pcap_factory', 'captures', 'AES128_SHA256_DH14_NOPFS_ICMP_rep01.pcap');
const port = process.env.DEMO_CDP_PORT || '9229';
const targetList = await fetch(`http://127.0.0.1:${port}/json/list`).then(response => response.json());
const target = targetList.find(item => item.type === 'page' && item.webSocketDebuggerUrl);
if (!target) throw new Error('No Chrome debugging page found. Open the local Vite app in Chrome first.');

const socket = new WebSocket(target.webSocketDebuggerUrl);
await new Promise((resolve, reject) => {
  socket.addEventListener('open', resolve, { once: true });
  socket.addEventListener('error', reject, { once: true });
});
let nextId = 1;
const pending = new Map();
socket.addEventListener('message', event => {
  const message = JSON.parse(event.data);
  if (!message.id) return;
  const callback = pending.get(message.id);
  if (!callback) return;
  pending.delete(message.id);
  message.error ? callback.reject(new Error(message.error.message)) : callback.resolve(message.result);
});
function call(method, params = {}) {
  return new Promise((resolve, reject) => {
    const id = nextId++;
    pending.set(id, { resolve, reject });
    socket.send(JSON.stringify({ id, method, params }));
  });
}
const evaluate = async expression => {
  const reply = await call('Runtime.evaluate', { expression, awaitPromise: true, returnByValue: true });
  if (reply.exceptionDetails) throw new Error(reply.exceptionDetails.text);
  return reply.result.value;
};
const waitFor = async (expression, timeoutMs = 30000) => {
  const started = Date.now();
  while (Date.now() - started < timeoutMs) {
    if (await evaluate(expression)) return;
    await new Promise(resolve => setTimeout(resolve, 400));
  }
  throw new Error(`Timed out waiting for ${expression}`);
};
const screenshot = async () => (await call('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false })).data;

try {
  await call('Page.enable');
  await call('Runtime.enable');
  await call('DOM.enable');
  await call('Emulation.setDeviceMetricsOverride', { width: 1280, height: 800, deviceScaleFactor: 1, mobile: false });
  await call('Page.navigate', { url: 'http://127.0.0.1:3000' });
  await waitFor("document.readyState === 'complete' && !!document.querySelector('header')");
  await evaluate("localStorage.setItem('vpn-theme', 'light'); location.reload()");
  await waitFor("document.readyState === 'complete' && document.documentElement.dataset.theme === 'light'");
  const frames = [{ caption: '1. Dashboard and capture upload', image: await screenshot() }];

  await evaluate("localStorage.setItem('vpn-theme', 'dark'); location.reload()");
  await waitFor("document.readyState === 'complete' && document.documentElement.dataset.theme === 'dark'");
  frames.push({ caption: '2. Dark theme across the analysis workspace', image: await screenshot() });

  const input = await call('Runtime.evaluate', { expression: "document.querySelector('#dropzone-file')", returnByValue: false });
  if (!input.result.objectId) throw new Error('Capture upload input was not found.');
  await call('DOM.setFileInputFiles', { objectId: input.result.objectId, files: [capture] });
  await waitFor("!!document.querySelector('#card-security-score')", 45000);
  frames.push({ caption: '3. Automated security score, risk, traffic and threat matrix', image: await screenshot() });

  await evaluate("document.querySelector('#btn-quick-report').click()");
  await waitFor("!!document.querySelector('#btn-report-exec')");
  await waitFor("document.body.innerText.includes('Generated by GROQ_LLM') || document.body.innerText.includes('AI narrative unavailable')", 30000);
  frames.push({ caption: '4. Executive report generated from capture evidence', image: await screenshot() });
  await evaluate("document.querySelector('.report-canvas.overflow-y-auto').scrollTop = 420");
  const proseReady = await evaluate("document.body.innerText.includes('Generated by GROQ_LLM')");
  frames.push({ caption: proseReady ? '5. Optional AI prose explains the supplied evidence' : '5. Optional AI narrative service status', image: await screenshot() });
  await evaluate("document.querySelector('#btn-report-tech').click()");
  await waitFor("document.querySelector('#btn-report-tech').className.includes('bg-stone-900')");
  await evaluate("document.querySelector('.report-canvas.overflow-y-auto').scrollTop = 0");
  frames.push({ caption: '6. Technical report and threat matrix', image: await screenshot() });

  await fs.mkdir(demoDir, { recursive: true });
  await fs.writeFile(path.join(demoDir, 'dark-dashboard-preview.png'), Buffer.from(frames[1].image, 'base64'));
  await fs.writeFile(path.join(demoDir, 'dark-analysis-preview.png'), Buffer.from(frames[2].image, 'base64'));
  await fs.writeFile(path.join(demoDir, 'dark-mode-preview.png'), Buffer.from(frames[3].image, 'base64'));
  await fs.writeFile(path.join(demoDir, 'dark-narrative-preview.png'), Buffer.from(frames[4].image, 'base64'));
  await fs.writeFile(path.join(demoDir, 'dark-technical-preview.png'), Buffer.from(frames[5].image, 'base64'));
  const encoded = await evaluate(`(async () => {
    const frames = ${JSON.stringify(frames.map(frame => ({ caption: frame.caption, src: `data:image/png;base64,${frame.image}` })))};
    const images = await Promise.all(frames.map(frame => new Promise((resolve, reject) => {
      const image = new Image(); image.onload = () => resolve(image); image.onerror = reject; image.src = frame.src;
    })));
    const canvas = document.createElement('canvas'); canvas.width = 1280; canvas.height = 800;
    const context = canvas.getContext('2d');
    const stream = canvas.captureStream(8);
    const mimeType = MediaRecorder.isTypeSupported('video/webm;codecs=vp8') ? 'video/webm;codecs=vp8' : 'video/webm';
    const recorder = new MediaRecorder(stream, { mimeType, videoBitsPerSecond: 1200000 });
    const chunks = []; recorder.ondataavailable = event => { if (event.data.size) chunks.push(event.data); };
    const stopped = new Promise((resolve, reject) => { recorder.onstop = resolve; recorder.onerror = reject; });
    recorder.start();
    for (let i = 0; i < frames.length; i++) {
      context.drawImage(images[i], 0, 0, canvas.width, canvas.height);
      context.fillStyle = 'rgba(9,18,31,.88)'; context.fillRect(0, canvas.height - 74, canvas.width, 74);
      context.fillStyle = '#ffffff'; context.font = 'bold 28px Arial'; context.fillText(frames[i].caption, 28, canvas.height - 27);
      await new Promise(resolve => setTimeout(resolve, 1800));
    }
    recorder.stop(); await stopped; stream.getTracks().forEach(track => track.stop());
    const blob = new Blob(chunks, { type: mimeType });
    return await new Promise((resolve, reject) => {
      const reader = new FileReader(); reader.onload = () => resolve(reader.result.split(',')[1]); reader.onerror = reject; reader.readAsDataURL(blob);
    });
  })()`);
  if (!encoded) throw new Error('Chrome did not produce a video recording.');
  const videoPath = path.join(demoDir, 'prototype-demo.webm');
  await fs.writeFile(videoPath, Buffer.from(encoded, 'base64'));
  console.log(`Recorded ${frames.length} scenes to ${videoPath}`);
} finally {
  socket.close();
}
